Add the Chinese version of README
luxonis/depthai-experiments pull request #109
Opened 2021-04-16 07:43 UTC by OAKChina

2021-04-16 14:44 UTC, Luxonis-Brandon commented
Thanks for doing all these!

2021-04-20 08:54 UTC, VanDavv requested changes
Thanks, @OAKChina! Saw some minor issues, but other than that, I think you've done great work here!

2021-04-20 08:54 UTC, VanDavv commented on collecting-training-data/README.md
> +[中文文档](README.zh-CN.md)
This script was moved [here](https://github.com/luxonis/depthai-experiments/tree/master/gen2-collecting-training-data) - could you update the README there? It also have a different content as new flags were added

2021-04-20 08:54 UTC, VanDavv commented on gen2-palm-detection/main.py
> +            "models/palm_detection_openvino_2020.1_4shave.blob", "palm", first=True
Can you compile the model to the latest 2021.3 OpenVINO? We have recently released a [blobconverter](https://pypi.org/project/blobconverter/) tool that can help you in compiling it faster

2021-04-20 08:54 UTC, VanDavv commented on gen2-palm-detection/main.py
> +                depthai.ColorCameraProperties.SensorResolution.THE_4_K
1080p is enough here
```suggestion
                depthai.ColorCameraProperties.SensorResolution.THE_1080_P
```

2021-04-20 08:54 UTC, VanDavv commented on gen2-palm-detection/main.py
> +            return False
```suggestion
            return
```

2021-04-22 06:01 UTC, OAKChina commented
Hi @VanDavv 
Thank you for your review, we are not familiar with github pull requests, please correct us if we did something wrong.

2021-04-22 10:41 UTC, VanDavv approved these changes
Thanks @OAKChina, it looks good now - will merge

2021-04-22 10:42 UTC, merged