added efficientDet experiment
luxonis/depthai-experiments pull request #124
Opened 2021-05-08 11:46 UTC by Erol444

Still have to clean up the code and make a proper readme

2021-05-08 20:44 UTC, Luxonis-Brandon commented
This will be sweet to have.  Thanks for putting it together!

2021-05-12 07:21 UTC, VanDavv requested changes
Have one minor request, other than that LGTM

2021-05-12 07:21 UTC, VanDavv commented on gen2-efficientDet/main.py
> +        data = qNn.tryGet()
I would change it to `in_nn`

2021-05-12 07:21 UTC, VanDavv commented on gen2-efficientDet/main.py
> +        frame = np.array(data).view(np.float16).reshape(shape).transpose(1, 2, 0).astype(np.uint8).copy()
it can be simplified to `np.array(inRgb.getData())`, we will avoid creating `data` variable which is later overwritten and is not used in this form

2021-05-13 11:04 UTC, VanDavv approved these changes
LGTM

2021-05-13 11:05 UTC, merged