added gen2 cumulative object counting example
luxonis/depthai-experiments pull request #145
Opened 2021-06-11 14:24 UTC by TannerGilbert

Cumulative object counting for both RGB camera or external videos.

Based on:
* [Tensorflow 2 Object Counting repository](https://github.com/TannerGilbert/Tensorflow-2-Object-Counting)
* [OpenCV People Counter](https://www.pyimagesearch.com/2018/08/13/opencv-people-counter/) 
* [tensorflow_object_counting_api](https://github.com/ahmetozlu/tensorflow_object_counting_api)

2021-06-11 15:11 UTC, Erol444 requested changes
Thank you for this demo, it will be useful to the community! The only thing I would change is to move the object tracking logic (if I understood it correctly) to the device using ObjectTracker node :)

2021-06-11 15:11 UTC, Erol444 commented on gen2-cumulative-object-counting/centroid_tracker.py
> +        return self.objects
From my understanding, this has the same functionality as ObjectTracker, just that it runs on the host?

2021-06-11 17:02 UTC, TannerGilbert commented
@Erol444 Didn't know there was a Tracker built into the depthai library. I just rewrote the code to use it instead of the CentroidTracker.

2021-06-11 19:46 UTC, Luxonis-Brandon commented
Sweet thanks @TannerGilbert !

2021-06-12 10:31 UTC, Erol444 commented
Just tried it out, works great! Only thing I would change is to have the model set by default (to the `/models/mobilenet-ssd.blob`) and possibly adding the video from the readme (if it's not too big) to the `demo` folder. Thanks!

2021-06-12 10:31 UTC, Erol444 approved these changes

2021-06-12 13:21 UTC, TannerGilbert commented
@Erol444 Done

2021-06-14 18:14 UTC, VanDavv commented on gen2-cumulative-object-counting/trackable_object.py
> +class TrackableObject:
Could we move the declaration of this class to the `main.py`? It would be one file less and this class is compact anyways

2021-06-14 18:32 UTC, TannerGilbert commented
@VanDavv Moved it into main.py

2021-06-16 07:10 UTC, VanDavv approved these changes
LGTM, thanks!

2021-06-16 07:11 UTC, merged