Add first-batch of examples
luxonis/depthai-experiments pull request #24
Opened 2020-12-23 13:54 UTC by VanDavv

The first batch of examples created accordingly to https://github.com/luxonis/depthai-docs-website/issues/102

Not all of the examples are working though, the status of them is listed below:

- [ ] `01_rgb_preview.py` working fine :heavy_check_mark: 
- [ ] `02_mono_preview.py` working fine :heavy_check_mark:
- [ ] `03_depth_preview.py` working fine :heavy_check_mark:
- [ ] `04_rgb_encoding.py` fails with the following error every time :x:

    ```
    Traceback (most recent call last):
      File "/home/vandavv/dev/luxonis/depthai-experiments/gen2_examples/04_rgb_encoding.py", line 20, in <module>
        device.startPipeline()
    RuntimeError: Couldn't read data from stream: __rpc_main
    ```
- [ ] `05_rgb_mono_encoding.py` fails with the following error every time :x:

    ```
    Traceback (most recent call last):
      File "/home/vandavv/dev/luxonis/depthai-experiments/gen2_examples/04_rgb_encoding.py", line 20, in <module>
        device.startPipeline()
    RuntimeError: Couldn't read data from stream: __rpc_main
    ```
- [ ] `06_rgb_full_resolution_saver.py` fails with the following error every time :x:

    ```
    Traceback (most recent call last):
      File "/home/vandavv/dev/luxonis/depthai-experiments/gen2_examples/04_rgb_encoding.py", line 20, in <module>
        device.startPipeline()
    RuntimeError: Couldn't read data from stream: __rpc_main
    ```
- [ ] `07_mono_full_resolution_saver.py` working fine :heavy_check_mark:
- [ ] `08_rgb_mobilenet.py` working fine :heavy_check_mark:
- [ ] `09_mono_mobilenet.py` outputs preview but no nn entries are returned :x:
- [ ] `10_mono_depth_mobilenetssd.py` fails with the following error every time :x:

    ```
    Traceback (most recent call last):
      File "/home/vandavv/dev/luxonis/depthai-experiments/gen2_examples/04_rgb_encoding.py", line 20, in <module>
        device.startPipeline()
    RuntimeError: Couldn't read data from stream: __rpc_main
    ```

@themarpe could you assist me in making all of them work?

2020-12-28 13:40 UTC, szabi-luxonis commented
@VanDavv `04_rgb_encoding.py` and `06_rgb_full_resolution_saver.py` has been fixed.
`06_rgb_full_resolution_saver.py` has very low framerate though, previewout was not meant for such high resolutions.

2020-12-28 13:50 UTC, szabi-luxonis commented
`06_rgb_full_resolution_saver.py` is meant to be the same as [this](https://github.com/luxonis/depthai-core/blob/gen2_resource_allocator/examples/src/camera_video_example.cpp) example? Equivalent to `color` stream on gen1

2020-12-28 14:07 UTC, VanDavv commented
@szabi-luxonis thanks! 
Just tested and they work indeed, awesome! 
WRT `06_rgb_full_resolution_saver.py` my idea was to show how to see / save the frames in the highest resolution available - as users will be able to decrease it or remove the preview (depending on their needs), the goal is to show the upper limit of what we can achieve

2020-12-28 14:10 UTC, szabi-luxonis requested changes

2020-12-28 14:10 UTC, szabi-luxonis commented on gen2_examples/06_rgb_full_resolution_saver.py
> +cam_rgb.setPreviewSize(2160, 3840)
width and height are swapped here

2021-01-03 14:04 UTC, themarpe commented
Thanks for all of the examples that are getting into this PR.

2 things I'd like to discuss briefly.

- Should we de facto default to `import depthai as dai` which makes the code look similar in both Python and C++ land?
- I suggest using Device(pipeline) abbreviation instead of the longer:
```
found, device_info = depthai.XLinkConnection.getFirstDevice(depthai.XLinkDeviceState.X_LINK_ANY_STATE)
if not found:
    raise RuntimeError("Device not found")
device = depthai.Device(pipeline, device_info)
```
As it will work correctly in case of 1 device in any state as well as more devices (except in case when all of them are already running - that case I think should throw as well)
The logic behind the default constructor of `Device(pipeline)` is the following: First search for any `UNBOOTED` devices, if not found search for any `BOOTLOADER` devices, and at last search for any `BOOTED` devices.
This also covers the work with 1 device connected to a debugger.

2021-01-07 12:25 UTC, themarpe approved these changes
Looks good - feel free to merge
ffmpeg calls are going to be revisited for `depthai-python` examples later on

2021-01-07 12:26 UTC, merged