Image quality assessment
luxonis/depthai-experiments pull request #320
Opened 2022-03-09 11:03 UTC by N950

This is an example of image quality assessment experiment running directly from OAK RGB camera

The model outputs 4 quality classes
* Clean
* Blur
* Occlusion
* Bright

2022-03-10 19:55 UTC, themarpe commented
@N950 
Any reason for using an older depthai library? I suggest bumping it up to 2.15

2022-03-10 20:04 UTC, N950 commented
@themarpe 
Thank you, just changed it and tested with 2.15

2022-03-11 11:21 UTC, tersekmatija requested changes
Could you also rename `image-quality-assessment` to `gen2-image-quality-assessment`, so it's aligned with other models

2022-03-11 11:21 UTC, tersekmatija commented on image-quality-assessment/main.py
> +NN_PATH = args.nn_path if args.nn_path else str(blobconverter.from_zoo(name="image_quality_assessment_256x256", zoo_type="depthai"))
I am working with @VanDavv to get this working.

2022-03-15 11:22 UTC, tersekmatija approved these changes
Thanks!

2022-03-15 11:39 UTC, tersekmatija commented
Thanks for that last fix!

2022-03-15 11:39 UTC, merged