Created parser for calibration files
luxonis/depthai-experiments pull request #328
Opened 2022-03-20 18:35 UTC by ZigiMigi

Created a parser for calibration files (.json), program is in python format and in jupyter notebook format. Parser reads files and sorts them by camera type. After the data is sorted it can be shown with histograms.

2022-03-28 18:19 UTC, themarpe commented
CC: @tersekmatija @VanDavv  @saching13 

Should we integrate this into some tool? 

+ @ZigiMigi (@saching13 ) does it take in account calibration file versioning?

2022-03-28 18:22 UTC, saching13 commented
> does it take in account calibration file versioning?
It does version 6 only as of now since there are like 10K+ of those alone. We can add version 5 too. But ignore the ones before. 

> Should we integrate this into some tool?

It would be good to have this as in internal tool. But if we streamline all our data as a database. 
Then we can do all this easily using a UI.

2022-03-28 22:22 UTC, tersekmatija commented
If we want it publicly available with UI we can integrate it into 'tools' repo that me and @VanDavv are working on for YoloV5 weights export.

Btw, what are the colors on the histogram plot? And can you add some labels to x and y axis + title please? @ZigiMigi

2022-03-29 00:14 UTC, saching13 commented
What would be more useful to users would be hosting these files on the cloud and have an endpoint to download them if the device id matches.

2022-03-29 06:23 UTC, ZigiMigi commented
Loking at the histogram from left to right, its x, y, z. 
And when you are ploting a histrogram from camera 1 and 2 together its x1, x2, y1, y2, z1, z2.
Will integrate the labeling today.

2022-03-29 07:13 UTC, tersekmatija commented
> What would be more useful to users would be hosting these files on the cloud and have an endpoint to download them if the device id matches.

So, just hosting static files and downloading them based on device ID? @saching13 

>  And when you are ploting a histrogram from camera 1 and 2 together its x1, x2, y1, y2, z1, z2.

Ah, I see. Makes sense. Maybe using `tab10` for one and `tab20` cmaps for two cameras might keep the colors consistent?
https://matplotlib.org/3.5.1/tutorials/colors/colormaps.html#qualitative @ZigiMigi

2022-03-29 07:24 UTC, ZigiMigi commented
Will try it and see if its better.

2022-03-29 08:50 UTC, ZigiMigi commented
Is something like this better? (this is tab20 cmap)

![Screenshot_1](https://user-images.githubusercontent.com/82703447/160572717-65a89990-e095-4fc0-b2d1-bb09a32f88bb.png)

2022-03-29 22:43 UTC, tersekmatija commented
Looking better. Can you also add some labels to x and y axis?

2022-04-06 17:10 UTC, saching13 commented
> So, just hosting static files and downloading them based on device ID? @saching13

Yes.

2022-04-06 17:23 UTC, saching13 requested changes
can you make this changes to both py and nnoetbook. I will take a look at the updated graphs. 

And as of intrinsics. It should be `f_x`, `f_y`, `c_x` and `c_y`

2022-04-06 17:23 UTC, saching13 commented on parser/parseFiles.py
> +        self.camera0["rotationMatrix"]["z"] = []
It is not XYZ. Change it to `RPY` (Roll, Pitch and Yaw).

2022-04-06 17:23 UTC, saching13 commented on parser/parseFiles.py
> +        self.camera0["intrinsicMatrix"]["z"] = []
What is XYZ here ?

2022-04-06 17:23 UTC, saching13 commented on parser/parseFiles.py
> +        self.camera1["rotationMatrix"]["z"] = []
RPY again

2022-05-06 21:35 UTC, merged