Add sequence number sync example
luxonis/depthai-experiments pull request #43
Opened 2021-01-19 19:59 UTC by VanDavv

This example demonstrates how to synchronize incoming frames using their sequence numbers. 
This allows displaying frames taken in exact same moment

2021-01-19 20:01 UTC, VanDavv commented
@themarpe is it possible now to make seq numbers from rgb camera to match the ones from mono cameras?
RGB starts earlier than Mono, and we had a sync mode in gen1 to tell the RGB camera to "wait" for mono cameras before 
increasing the sequence number value on it's frames.

2021-01-19 22:06 UTC, szabi-luxonis requested changes

2021-01-19 22:06 UTC, szabi-luxonis commented on gen2-seq-num-sync/requirements.txt
> +numpy==1.18.3
numpy version doesn't match the one that comes with opencv 4.5. May cause issues.
`numpy==1.19.5`

2021-01-21 00:39 UTC, szabi-luxonis approved these changes
LGTM

2021-01-21 17:55 UTC, merged